

[fsps_full]
    files = [
        'fsps_full/tweak_fsps_QSF_12_v3_001.dat',
        'fsps_full/tweak_fsps_QSF_12_v3_002.dat',
        'fsps_full/tweak_fsps_QSF_12_v3_003.dat',
        'fsps_full/tweak_fsps_QSF_12_v3_004.dat',
        'fsps_full/tweak_fsps_QSF_12_v3_005.dat',
        'fsps_full/tweak_fsps_QSF_12_v3_006.dat',
        'fsps_full/tweak_fsps_QSF_12_v3_007.dat',
        'fsps_full/tweak_fsps_QSF_12_v3_008.dat',
        'fsps_full/tweak_fsps_QSF_12_v3_009.dat',
        'fsps_full/tweak_fsps_QSF_12_v3_010.dat',
        'fsps_full/tweak_fsps_QSF_12_v3_011.dat',
        'fsps_full/tweak_fsps_QSF_12_v3_012.dat',
    ]
    redshift_dependent = false
    attribution = "eazy, fsps"

[fsps_Larson22]
    files = [
        'fsps_full/tweak_fsps_QSF_12_v3_001.dat',
        'fsps_full/tweak_fsps_QSF_12_v3_002.dat',
        'fsps_full/tweak_fsps_QSF_12_v3_003.dat',
        'fsps_full/tweak_fsps_QSF_12_v3_004.dat',
        'fsps_full/tweak_fsps_QSF_12_v3_005.dat',
        'fsps_full/tweak_fsps_QSF_12_v3_006.dat',
        'fsps_full/tweak_fsps_QSF_12_v3_007.dat',
        'fsps_full/tweak_fsps_QSF_12_v3_008.dat',
        'fsps_full/tweak_fsps_QSF_12_v3_009.dat',
        'fsps_full/tweak_fsps_QSF_12_v3_010.dat',
        'fsps_full/tweak_fsps_QSF_12_v3_011.dat',
        'fsps_full/tweak_fsps_QSF_12_v3_012.dat',
        'Larson22/binc100z001age6_cloudy.dat',
        'Larson22/binc100z001age65_cloudy.dat',
        'Larson22/binc100z001age7_cloudy.dat',
    ]
    redshift_dependent = false
    attribution = "fsps, Larson et al. (2022)"


